name: Build and Release
on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        device: [d1, d1xks, d2x, d2s, d2xks]
    runs-on: ubuntu-24.04
    steps:
      - name: "⏰Set Time Zone to Beijing"
        run: |
          sudo timedatectl set-timezone "Asia/Shanghai"

      - name: "🚄Set up build environment"
        run: |
          sudo apt-get update
          sudo apt-get install -y git-core flex bison build-essential zip curl zlib1g-dev libc6-dev-i386 lib32z1-dev unzip

      - name: "⭐Checkout repository with submodules"
        uses: actions/checkout@v7
        with:
          submodules: true

      - name: "💡 Setup KernelSU-Next"
        run: |
          if [ -d "./KernelSU" ]; then rm -rf "./KernelSU"; fi
          if [ -d "./drivers/KernelSU" ]; then rm -rf "./drivers/KernelSU"; fi
          
          echo "🔧 Using legacy-susfs-v2 branch from sidex15"
          git clone https://github.com/sidex15/KernelSU-Next.git KernelSU-Next
          cd KernelSU-Next
          git fetch --all
          git checkout origin/legacy-susfs-v2
          cd ..
          curl -LSs "https://raw.githubusercontent.com/sidex15/KernelSU-Next/stable/kernel/setup.sh" | bash -s origin/legacy-susfs-v2


      - name: "🐎Build for specific device"
        run: ./build.sh -m ${{ matrix.device }} -k Y -r N

      - name: "💫Prepare ZIP files for upload"
        run: |
          mkdir -p ${{ github.workspace }}/build/out/zip_files
          find ${{ github.workspace }}/build/out/ -type f -name "*.zip" -exec cp {} ${{ github.workspace }}/build/out/zip_files/ \;

      - name: "😎Upload ZIP files as artifact"
        uses: actions/upload-artifact@v7
        with:
          name: "ExtremeKRNL-Quant-Susfs-${{ matrix.device }}"
          path: ${{ github.workspace }}/build/out/zip_files/
