name: Build and Release
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: "⏰Set Time Zone to Beijing"
        run: |
          sudo timedatectl set-timezone "Asia/Shanghai"

      - name: "🚄Set up build environment"
        run: |
          sudo apt-get update
          sudo apt-get install -y git-core flex bison build-essential zip curl zlib1g-dev libc6-dev-i386 lib32z1-dev unzip xz-utils cpio

      - name: "⭐Checkout repository with submodules"
        uses: actions/checkout@v7
        with:
          submodules: true

      - name: "💡 Setup KernelSU-Next"
        run: |
          if [ -d "./KernelSU" ]; then rm -rf "./KernelSU"; fi
          if [ -d "./drivers/KernelSU" ]; then rm -rf "./drivers/KernelSU"; fi
          
          echo "🔧 Using KernelSU-Next"
          curl -LSs "https://raw.githubusercontent.com/KernelSU-Next/KernelSU-Next/next/kernel/setup.sh" | bash -s legacy


      - name: "🐎Build Unified Kernel Package"
        run: |
          chmod +x build.sh
          ./build.sh -m all -k y -r n

      - name: "💫Prepare Unified ZIP for upload"
        run: |
          mkdir -p ${{ github.workspace }}/upload
          cp build/*.zip ${{ github.workspace }}/upload/
          echo "=== Files in upload directory ==="
          ls -la ${{ github.workspace }}/upload/

      - name: "😎Upload Unified ZIP as artifact"
        uses: actions/upload-artifact@v7
        with:
          name: "ExtremeKRNL-Unified-Package"
          path: ${{ github.workspace }}/upload/*.zip
